### ISSUE TITLE
No labels after running autoimpute

### ISSUE THREAD

**Issue by dtm2117** [divyanshu-talwar/AutoImpute#1]
Hello,

I have run autoimpute on a scRNA-seq .csv file. The output of a .mat file is then read into R using the R.matlab package. Unfortunately the array does not have cell names or gene names. Are they the same as the original .csv?

best,
David

**Comment by divyanshu-talwar** [comment]
Hey David,

As discussed in the `README`, in the AutoImpute pipeline, we first pre-process the new dataset and then feed it as input to `AutoImpute.py`. What I gather from your question is that you might be interchanging the order of performing these steps.
Coming back to your question, the R script (`pre-process.R`) writes the output matrix retaining the cell and gene names (refer [line](https://github.com/divyanshu-talwar/AutoImpute/blob/26b09794439c7fa50b8a40cf16cd84219deef76d/AutoImpute%20Model/Pre-processing/pre-process.R#L27) in the code). `AutoImpute.py`, however, clips out these cell and gene names retaining matrix structure fed as input to it (output of `pre-process.R`) at all times, keeping the cell and gene names of the input and output of `AutoImpute.py` the same.
