### ISSUE TITLE
format for imputed matrix

### ISSUE THREAD

**Issue by chelseaju** [divyanshu-talwar/AutoImpute#2]
I tried to follow the readme to run the analysis for the blakeley.csv dataset. After running AutoImpute.py, it automatically writes the imputed matrix to "imputed_matrix.mat". I noticed that it is a MATLAB matrix. For any downstream analysis, we will need to extract the values out first. Is it possible to output the impute matrix as a plain text? such as .csv or .txt?  Thanks.

**Comment by divyanshu-talwar** [comment]
Hey,

The [line](https://github.com/divyanshu-talwar/AutoImpute/blob/0e3d4493a5ca7badd76edf18e689a269b9f1f013/AutoImpute%20Model/AutoImpute.py#L181) in `AutoImpute/AutoImpute.py` saves the `imputed_count_matrix` in the MATLAB matrix format. You could edit the same and save the `imputed_count_matrix` in any format of your choice.
You could use [numpy.savetxt](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.savetxt.html) - For saving a numpy matrix in `.txt` or `.csv` format

**Comment by divyanshu-talwar** [comment]
Hey,

The [line](https://github.com/divyanshu-talwar/AutoImpute/blob/0e3d4493a5ca7badd76edf18e689a269b9f1f013/AutoImpute%20Model/AutoImpute.py#L181) in `AutoImpute\ Model/AutoImpute.py` saves the `imputed_count_matrix` in the MATLAB matrix format. You could edit the same and save the `imputed_count_matrix` in any format of your choice.
You could use [numpy.savetxt](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.savetxt.html) - For saving a numpy matrix in `.txt` or `.csv` format.

**Comment by divyanshu-talwar** [comment]
Hey,

The [line](https://github.com/divyanshu-talwar/AutoImpute/blob/0e3d4493a5ca7badd76edf18e689a269b9f1f013/AutoImpute%20Model/AutoImpute.py#L181) in `AutoImpute\ Model/AutoImpute.py` saves the `imputed_count_matrix` in the MATLAB matrix format. You could edit the same and save the `imputed_count_matrix` in any format of your choice.
[numpy.savetxt](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.savetxt.html) could be used for saving a numpy matrix in `.txt` or `.csv` format.
