### ISSUE TITLE
--data input error

### ISSUE THREAD

**Issue by MarinusVL** [divyanshu-talwar/AutoImpute#4]
giving any data argument gives the error:
 Please make sure that your processed dataset is in data/ in .mat or .csv format and you have entered the filename as data parameter. e.g. blakeley.csv

to solve this remove "nargs = '+'," from the autoimpute.py script and change it to:

# Data
parser.add_argument('--data', type = str, default='blakeley.csv', help = "Dataset to run the script on. Can choose from : ['blakeley.csv', 'jurkat-293T.mat', 'kolodziejczyk.csv', 'PBMC.csv', 'preimplantation.mat', 'quake.csv', 'usoskin.csv', 'zeisel.csv']")

**Comment by divyanshu-talwar** [comment]
Thanks for reporting the bug as well as the fix @MarinusVL , will update the script shortly.
